#!/bin/bash
#PBS -M jfear@ufl.edu
#PBS -m n
#PBS -r n
#PBS -q bio
#PBS -o /scratch/lfs/mcintyre/cegs_ase_paper/scripts/PBS_LOGS/bayesian/
#PBS -e /scratch/lfs/mcintyre/cegs_ase_paper/scripts/PBS_LOGS/bayesian/
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=300mb
#PBS -t 1-500

module load R/3.0.2

# Set Directories
    PROJ=/scratch/lfs/mcintyre/cegs_ase_paper
    RPROG=$PROJ/scripts/emp_bayesian/PG_model_empirical_q456.r

    OUTDIR=$PROJ/emp_bayesian/PG_model/split
    if [ ! -e $OUTDIR ] ; then mkdir -p $OUTDIR; fi
    
    LOGS=$OUTDIR/logs
    if [ ! -e $LOGS ] ; then mkdir -p $LOGS; fi

# Set Files
    INPUT=$PROJ/emp_bayesian/input/split/split_${PBS_ARRAYID}.csv
    OUTPUT=$OUTDIR/split_${PBS_ARRAYID}.csv
    MYLOG=$LOGS/split_${PBS_ARRAYID}.log

    echo "Running $INPUT [`date`]" > $MYLOG
    Rscript $RPROG $INPUT $OUTPUT &>>$MYLOG
