#!/bin/bash
#PBS -M jfear@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /bio/mcintyre/cegs/scripts/PBS_LOGS/package_fb551_genome/
#PBS -l walltime=11:00:00
#PBS -l nodes=1:ppn=4
#PBS -l pmem=1gb

PROJ=/bio/mcintyre/cegs
NAME=genome
NUMPROCS=4

# PACK Alignments
cd $PROJ/mpileup_fb551_$NAME
for FILE in *.mpileup;
do
    gzip $FILE &

    while [ $(jobs -p | wc -l) -ge $NUMPROCS ]
    do
        sleep 60
    done

done
wait

tar -czvf logs.tar.gz ./logs
md5sum *.gz > md5sum

rm -r logs
