#!/bin/bash
#PBS -M jfear@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/cegs/scripts/PBS_LOGS/parse_aln_logs_fb551_canonical_junctions/
#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=900mb

module load python/2.7.3 

PROJ=/scratch/lfs/mcintyre/cegs
OUTPUT=$PROJ/aln_fb551_canonical_junctions_nodup
LOGS=$OUTPUT/aln_logs
SCRIPTS=/scratch/lfs/mcintyre/python.git

for I in {1..972}
do
    DESIGN_FILE=$PROJ/design_files/CEGS_combined_w_platek_lines_design.txt
    DESIGN=$(sed -n "${I}p" $DESIGN_FILE)

    IFS=',' read -ra ARRAY <<< "$DESIGN"

    LINE=${ARRAY[0]}
    MV=${ARRAY[1]}
    REP=${ARRAY[2]}
    TECHREP=${ARRAY[3]}
    
    echo "$LINE $MV $REP" 
    if [ -s $LOGS/${LINE}_${MV}${REP}.${TECHREP}_bowtie.log ]
    then
        python ${SCRIPTS}/logParser.py \
            -bowtie $LOGS/${LINE}_${MV}${REP}.${TECHREP}_bowtie.log \
            -treatment $LINE $MV $REP $TECHREP \
            -o $OUTPUT/aln_summary_fb551_canonical_junctions_`date +%Y%m%d`.csv
    fi
done
