#!/bin/bash
#PBS -M fnew@ufl.edu
#PBS -m n
#PBS -N tajimaD_X
#PBS -q mcintyre
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/dsim_pop/scripts/PBS_LOGS/tajimaD
#PBS -l walltime=00:30:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1GB

module load vcftools

PROJ=/scratch/lfs/mcintyre/dsim_pop
#LIST=$PROJ/Haplotype_Caller_merged/split_vcf/chrX/windowList_names.tsv
#    DESIGN=$(sed -n "${PBS_ARRAYID}p" $LIST)
#    NAME=`basename "$DESIGN" .vcf`

#VCF=$PROJ/Haplotype_Caller_merged/split_vcf/chrX/chrom_X/${NAME}.vcf
OUT=$PROJ/checking_gatk_output/tajima_d_split_vcf/chrX
    
    if [ ! -e $OUT ]; then mkdir -p $OUT; fi

#vcftools --vcf $VCF --TajimaD 10000 --out $OUT/${NAME}


for I in {1..2085}
do
    LIST=$PROJ/checking_gatk_output/split_vcf/chrX_10kb/windowList_names.tsv
    DESIGN=$(sed -n "${I}p" $LIST)
    NAME=`basename "$DESIGN" .vcf`
    VCF=$PROJ/checking_gatk_output/split_vcf/chrX_10kb/chrom_X/${NAME}.vcf
    
    vcftools --vcf $VCF --TajimaD 10000 --out $OUT/${NAME}
done
