#!/bin/bash
#PBS -M fnew@ufl.edu
#PBS -m n
#PBS -N vcf_split
#PBS -q mcintyre
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/dsim_pop/scripts/PBS_LOGS/vcf_split
#PBS -l walltime=5:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=15GB
#PBS -t 1-6

module load plink

# SET DIRECTORIES

PROJ=/scratch/lfs/mcintyre/dsim_pop
LIST=$PROJ/lists/chrom_list.txt
    DESIGN=$(sed -n "${PBS_ARRAYID}p" $LIST)
    NAME=`basename "$DESIGN"`

VCF=$PROJ/Haplotype_Caller_merged/vcf_by_chrom/filter_10permiss_nolab_nomel_${NAME}.recode.vcf
OUT=$PROJ/plink/${NAME}

    if [ ! -e $OUT ]; then mkdir -p $OUT; fi

cd $OUT
plink --vcf $VCF --r2 square yes-really --allow-extra-chr --out $OUT/chr${NAME}_matrix_ld
