#/bin/bash
#PBS -M fnew@ufl.edu
#PBS -m n
#PBS -N vcftools
#PBS -q bigmem
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/dsim_pop/scripts/PBS_LOGS/vcftools
#PBS -l walltime=1:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=2Gb

module load vcftools

PROJ=/scratch/lfs/mcintyre/dsim_pop
VCF=$PROJ/Haplotype_Caller_merged/simulans_multisamp_all_chr.vcf
OUT=$PROJ/vcftools_output

vcftools --vcf $VCF --het --out $OUT/simulans_het_per_ind

