#/bin/bash
#PBS -M fnew@ufl.edu
#PBS -m n
#PBS -N h12_4
#PBS -q mcintyre
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/dsim_pop/scripts/PBS_LOGS/h12
#PBS -l walltime=3:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=3Gb
#PBS -t 1-6

module load bedtools


# Set up directories
PROJ=/scratch/lfs/mcintyre/dsim_pop
LIST=$PROJ/lists/chrom_list.txt
    DESIGN=$(sed -n "${PBS_ARRAYID}p" $LIST)
    NAME=`basename "$DESIGN"`

# Bed A is the reference file with genes, Bed B is the bed file with peaks.
BEDA=/scratch/lfs/mcintyre/references/dsimV2_w501/dsim_r2.01_genes.bed
BEDB=$PROJ/h12/output/bed_files/chr${NAME}_top_peaks.txt

#Output the swept genes
OUT=$PROJ/h12/output/chr${NAME}_genes_top_peaks.txt


# Call the program
bedtools intersect -a $BEDA -b $BEDB   -f 1 -wa -wb > $OUT
