#!/bin/bash
#PBS -M fnew@ufl.edu
#PBS -m n
#PBS -N snpeff
#PBS -q mcintyre
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/dsim_pop/scripts/PBS_LOGS/snpeff
#PBS -l walltime=11:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=5GB

module load snpeff/4.1
module load java

PROJ=/scratch/lfs/mcintyre/dsim_pop
VCF=$PROJ/Haplotype_Caller_merged/sim_biall_10per_miss_snpeff2.vcf
OUT=$PROJ/snpeff/pos_indiv_filtering
   if [ ! -e $OUT ]; then mkdir -p $OUT; fi




snpEff -c $PROJ/snpEff.config -v dsim_r2.01  $VCF > $OUT/dsim_snpeff_filt_indiv_10per_miss.ann.vcf
#java -jar $HPC_SNPEFF_BIN/snpEff.jar -c $HPC_SNPEFF_CONF/snpEff.config -v dsim_r2.01  $VCF > $OUT/dsim_snpeff.ann.vcf

#Run snpeff...
#java -jar $HPC_SNPEFF_BIN/snpEff.jar -c $HPC_SNPEFF_CONF/snpEff.config download -v dsim_r2.01  
