#!/bin/bash
#PBS -M fnew@ufl.edu
#PBS -m n
#PBS -N vcf_split
#PBS -q mcintyre
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/dsim_pop/scripts/PBS_LOGS/vcf_split
#PBS -l walltime=5:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1GB
#PBS -t 1-6

module load vcftools

# Set directories

PROJ=/scratch/lfs/mcintyre/dsim_pop
LIST=$PROJ/lists/chrom_list.txt
    DESIGN=$(sed -n "${PBS_ARRAYID}p" $LIST)
    NAME=`basename "$DESIGN"`
#REF=/scratch/lfs/mcintyre/references/dsimV2_w501
#VCF=$PROJ/Haplotype_Caller_merged/filter_10permiss_nolab_nomel.recode.vcf
#OUT=$PROJ/Haplotype_Caller_merged/vcf_by_chrom

## Run on the no missing data
VCF=$PROJ/Haplotype_Caller_merged/no_missing/no_missing_biall_chr_nolab_nomel_noindel.recode.vcf
OUT=$PROJ/Haplotype_Caller_merged/no_missing/vcf_by_chrom

#vcftools --vcf $VCF --bed $REF/dsim_r2.01_${NAME}.bed --recode --out $OUT/filter_biall_chr_nolab_${NAME} 
vcftools --vcf $VCF --chr $NAME --recode --out $OUT/no_missing_biall_chr_nolab_nomel_noindel_${NAME}
