#/bin/bash
#PBS -M fnew@ufl.edu
#PBS -m n
#PBS -N hap_freq_viz
#PBS -q mcintyre
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/dsim_pop/scripts/PBS_LOGS/h12
#PBS -l walltime=3:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=3Gb
#PBS -t 1

module load R

# Set up directories
PROJ=/scratch/lfs/mcintyre/dsim_pop
LIST=$PROJ/lists/chrom_list.txt
    DESIGN=$(sed -n "${PBS_ARRAYID}p" $LIST)
    NAME=`basename "$DESIGN"`

SCRIPT=$PROJ/scripts/hapSpectrum_viz.R

#DATA=$PROJ/checking_gatk_output/chr${NAME}_H12_peaks.txt
#OUT=$PROJ/checking_gatk_output/chr${NAME}_hapSpectrum.pdf

DATA=$PROJ/h12/output_new_window_test/chr${NAME}_h12_peaks.txt
OUT=$PROJ/h12/output_new_window_test/chr${NAME}_hapSpectrum.pdf


# Call the program
Rscript $SCRIPT $DATA $OUT 10 170
