#/bin/bash
#PBS -M fnew@ufl.edu
#PBS -m n
#PBS -N h12
#PBS -q mcintyre
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/dsim_pop/scripts/PBS_LOGS/h12
#PBS -l walltime=3:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=3Gb
#PBS -t 1

module load python


# Set up directories
PROJ=/scratch/lfs/mcintyre/dsim_pop
LIST=$PROJ/lists/chrom_list.txt
    DESIGN=$(sed -n "${PBS_ARRAYID}p" $LIST)
    NAME=`basename "$DESIGN"`

SCRIPT=$PROJ/scripts/H12_H2H1.py

#DATA=$PROJ/checking_gatk_output/chr${NAME}_for_h12.csv
#DATA=$PROJ/h12/all_chrom_for_h12.csv
DATA=$PROJ/h12/chr${NAME}_for_h12.csv

#OUT=$PROJ/checking_gatk_output/chr${NAME}_H12_output.txt
#OUT=$PROJ/h12/all_chrom_H12.txt
OUT=$PROJ/h12/output_new_window_test/chr${NAME}_h12_output.txt

# Call the program
python $SCRIPT $DATA 170 -o $OUT -w 800 -j 100 -d 0
#python $SCRIPT $DATA 169 -o $OUT -w 400 -j 50 -d 0
