#!/bin/bash
#PBS -M jrbnewman@ufl.edu
#PBS -m n
#PBS -r n
#PBS -q bio
#PBS -j oe
#PBS -o /scratch/lfs/sugrue/scripts/PBS_LOGS/mpileup_strand
#PBS -l walltime=6:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=12gb
#PBS -t 1-64

module load samtools/0.1.19

#### Set Directories
    PROJ=/scratch/lfs/sugrue

#### Because I am using an PBS Array I am pulling LINE:MV:REP from an external CSV with all possible combinations
    DESIGN_FILE=$PROJ/design_files/sugrue_file_list.csv
    DESIGN=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)
    IFS=',' read -ra ARRAY <<< "$DESIGN"

    C=${ARRAY[0]}
    NUM=${ARRAY[1]}
    SAMP=${ARRAY[2]}
    LANE=${ARRAY[3]}
    READ=${ARRAY[4]}
    BIN=${ARRAY[5]}

    NAME=${C}-${NUM}_${SAMP}_${LANE}_${READ}_${BIN}

    # Create OUTPUT directory if needed.
        OUTPUT=$PROJ/mpileup_distinct_strand
        if [ ! -e $OUTPUT ]; then mkdir -p $OUTPUT; fi

        SAMOUT=$PROJ/bwa_mem_aln_strand
        if [ ! -e $SAMOUT ]; then mkdir -p $SAMOUT ;fi

        BAMOUT=$PROJ/aln_hg19_bam_strand
        if [ ! -e $BAMOUT ]; then mkdir -p $BAMOUT; fi

    # Create LOG directory and start log
        LOGS=$OUTPUT/logs 
        if [ ! -e $LOGS ]; then mkdir -p $LOGS; fi
        MYLOG=$LOGS/${NAME}.log
        printf "`date` $NAME PBS_ID:$PBS_ARRAYID HOSTNAME:$HOSTNAME \n\n" > "${MYLOG}"

#### References
    REF=$PROJ/references/hg19_all_chr_for_bedtools.fa

    #if [ ! -e $REF.fai ]
    #then
    #    samtools faidx $REF
    #fi

#### Convert SAM to BAM and make mpileups
    SAM=$PROJ/bwa_mem_aln_se/${NAME}.sam 
    FWD=$SAMOUT/${NAME}_fwd.sam
    REV=$SAMOUT/${NAME}_rev.sam
    BAMF=$BAMOUT/${NAME}_fwd
    BAMR=$BAMOUT/${NAME}_rev

    printf "<-------------------- Convert SAM to BAM -------------------->" >> "${MYLOG}"
    echo `date`": Starting SAM to BAM conversion" >> "${MYLOG}"
    samtools view -F 0x10 -S $SAM > $FWD
    samtools view -f 0x10 -S $SAM > $REV
    samtools view -ut $REF.fai -o $BAMF.bam $FWD 2>> "${MYLOG}" 
    samtools view -ut $REF.fai -o $BAMR.bam $REV 2>> "${MYLOG}"
    samtools sort -m 1000000000 $BAMF.bam $BAMF.sorted 2>> "${MYLOG}"
    samtools sort -m 1000000000 $BAMR.bam $BAMR.sorted 2>> "${MYLOG}"
    samtools index $BAMF.sorted.bam >> "${MYLOG}"
    samtools index $BAMR.sorted.bam >> "${MYLOG}"

    echo `date`": Finished SAM to BAM conversion" >> "${MYLOG}"

#### Make mpielup
    PILEF=$OUTPUT/${NAME}_fwd.mpileup
    PILER=$OUTPUT/${NAME}_rev.mpileup

    printf "<-------------------- Convert BAM to MPILEUP -------------------->" >> "${MYLOG}"
    echo `date`": Generating pileup" >> "${MYLOG}"
    samtools mpileup -d 1000000000 -f $REF $BAMF.sorted.bam  > $PILEF 2>> "${MYLOG}"
    samtools mpileup -d 1000000000 -f $REF $BAMR.sorted.bam  > $PILER 2>> "${MYLOG}"

echo `date`": Finished Script complete" >> "${MYLOG}"
