#!/bin/bash
#PBS -M fnew@ufl.edu
#PBS -m n
#PBS -q mcintyre
#PBS -N sugrueSplit
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/sugrue/scripts/PBS_LOGS/split_dups
#PBS -l walltime=5:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=10Gb
#PBS -t 1-64

module load python/2.7.3

## Set Directories

    PROJ=/scratch/lfs/sugrue
    ORIG=$PROJ/untrimmed_data/fastq
    OUTDIR=$PROJ/qc/splitdups
    ONAME=$PROJ/qc/splitdups_counts
    OUTFILES=$PROJ/qc/splitdups_tables
    LOG=$OUTDIR/logs

    if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi
    if [ ! -e $OUTFILES ]; then mkdir -p $OUTFILES; fi
    if [ ! -e $ONAME ]; then mkdir -p $ONAME; fi
    if [ ! -e $LOG ]; then mkdir -p $LOG; fi

## Pull info from design file    

    DESIGN_FILE=$PROJ/design_files/sugrue_file_list.csv
    DESIGN=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)
    IFS=',' read -ra ARRAY <<< "$DESIGN"

    C=${ARRAY[0]}
    NUM=${ARRAY[1]}
    SAMP=${ARRAY[2]}
    LANE=${ARRAY[3]}
    READ=${ARRAY[4]}
    BIN=${ARRAY[5]}

    NAME=${C}-${NUM}_${SAMP}_${LANE}_${READ}_${BIN}

    python /scratch/lfs/mcintyre/python.git/fastqSplitDups.py -r1 $ORIG/$NAME.fastq  --outdir $OUTDIR -o ${ONAME}/${NAME}.csv -t $OUTFILES/${NAME}_table.txt -g $LOG/${NAME}.log

