#!/bin/bash
#PBS -M jfear@ufl.edu
#PBS -m n
#PBS -r n
#PBS -q bio
#PBS -o /scratch/lfs/mcintyre/cegs_ase_paper/scripts/PBS_LOGS/bayesian/
#PBS -e /scratch/lfs/mcintyre/cegs_ase_paper/scripts/PBS_LOGS/bayesian/
#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=500mb
#PBS -t 1-500

module load R/3.0.2

# Set Directories
PROJ=/scratch/lfs/mcintyre/cegs_ase_paper
RPROG=$PROJ/scripts/typeI_error/emp_PG_DNA_Random_NO_YESAI_YESBIAS.r

OUTDIR=$PROJ/typeI_error/output/split
if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi

# Set Files
INPUT=$PROJ/typeI_error/input/split/simulated_YESAI_YESBIASRequal1d5Poisson_${PBS_ARRAYID}.csv
OUTPUT=$OUTDIR/simulated_YESAI_YESBIASRequal1d5Poisson_results_${PBS_ARRAYID}.csv

Rscript $RPROG $INPUT $OUTPUT
