#!/bin/bash
#PBS -M jfear@ufl.edu
#PBS -m n
#PBS -r n
#PBS -q bio
#PBS -o /scratch/lfs/mcintyre/cegs_ase_paper/scripts/PBS_LOGS/miss/
#PBS -e /scratch/lfs/mcintyre/cegs_ase_paper/scripts/PBS_LOGS/miss/
#PBS -l walltime=48:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=500mb
#PBS -t 1-500

module load R/3.0.2

PROJ=/scratch/lfs/mcintyre/cegs_ase_paper
SCRIPT=$PROJ/scripts/typeI_error/PG_model_empirical_qRange.r
line=r365

OUTDIR=$PROJ/pipeline_output/typeI_error/output/${line}_miss_split_qRange
if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi

for QTRUE in 35 375 4 425 45 46 47 48 49 50 51 52 53 54 55 575 6 625 65; do

    INPUT=$PROJ/pipeline_output/typeI_error/input/${line}_miss_split/${line}_misspecification_qTrue0${QTRUE}_sim_${PBS_ARRAYID}.csv
    OUTPUT=$OUTDIR/${line}_misspecification_results_qTrue0${QTRUE}_sim_${PBS_ARRAYID}.csv

    Rscript $SCRIPT $INPUT $OUTPUT 0.$QTRUE
done
