#!/bin/bash
#PBS -M jfear@ufl.edu
#PBS -m n
#PBS -r n
#PBS -q bio
#PBS -o /scratch/lfs/mcintyre/cegs_ase_paper/scripts/PBS_LOGS/bayesian/
#PBS -e /scratch/lfs/mcintyre/cegs_ase_paper/scripts/PBS_LOGS/bayesian/
#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=500mb
#PBS -t 1-500

module load R/3.0.2

# Set Directories
PROJ=/scratch/lfs/mcintyre/cegs_ase_paper
RPOG=$PROJ/scripts/typeI_error/r101_emp_PG_DNA_Random_NOAI_NOBIAS.r

OUTDIR=$PROJ/typeI_error/output/r101_split
if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi

INPUT=$PROJ/typeI_error/input/r101_split/r101_simulated_NOAI_NOBIASRequal1Poisson_${PBS_ARRAYID}.csv
OUTPUT=$OUTDIR/r101_simulated_NOAI_NOBIASRequal1Poisson_results_${PBS_ARRAYID}.csv

Rscript $RPOG $INPUT $OUTPUT
