#!/bin/bash
#PBS -M jrbnewman@ufl.edu
#PBS -N bwa_distinct
#PBS -m n
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/cegs2.0/scripts/PBS_LOGS
#PBS -l walltime=4:00:00
#PBS -l nodes=1:ppn=4
#PBS -l pmem=6gb
#PBS -t 2-96


# Load modules

module load bwa/0.7.7
module load python/2.7.3
module load samtools

#Set directories

    PROJ=/scratch/lfs/mcintyre/cegs2.0
    QC=/scratch/lfs/mcintyre/cegs2.0/qc_plate1
    ORIG=$PROJ/fastq_split_dups_pe
    OUTPUT=$QC/bwa_mem_aln_pe_distinct
    if [ ! -e $OUTPUT ]; then mkdir -p $OUTPUT; fi

    ## Output folder for split SAM files
    SPLITSAM=$OUTPUT/bwa_split
    if [ ! -e $SPLITSAM ]; then mkdir -p $SPLITSAM; fi


## Design file

## Design file
     DESIGN_FILE=$PROJ/design_files/design_plate1_aln.csv

     DESIGN=$(cat $DESIGN_FILE | head -n $PBS_ARRAYID | tail -n 1)
     IFS=',' read -ra ARRAY <<< "$DESIGN"

UFL=${ARRAY[0]}
PROJNUM=${ARRAY[1]}
PLATE=${ARRAY[2]}
WELL=${ARRAY[3]}
BARCODE=${ARRAY[4]}
LANE=${ARRAY[5]}
REP=${ARRAY[6]}
INDEX=${ARRAY[7]}

READ1=${UFL}_${PROJNUM}_${PLATE}_${WELL}_${BARCODE}_${LANE}_R1_${INDEX}
READ2=${UFL}_${PROJNUM}_${PLATE}_${WELL}_${BARCODE}_${LANE}_R2_${INDEX}
NAME=${UFL}_${PROJNUM}_${PLATE}_${WELL}_${BARCODE}_${BARCODE}_${INDEX}


## set references
    REF=/scratch/lfs/mcintyre/references/dmel_fb557/bwa_dmel-all-chromosome-r5.57
    FASTA=/scratch/lfs/mcintyre/references/dmel_fb557/bwa_dmel-all-chromosome-r5.57.fasta

#### create bwa-mem reference
## should already done, but is included here in case

#    bwa index -p $REF -a bwtsw $FASTA


#### run bwa-mem
    bwa mem -t 4 -M $REF $ORIG/${READ1}_distinct.fq $ORIG/${READ2}_distinct.fq > $OUTPUT/${NAME}.sam

#### parse bwa alignment file
    python $PROJ/scripts/BWASplitSAM_4mai.py -fq1 $ORIG/${READ1}_distinct.fq -fq2 $ORIG/${READ2}_distinct.fq -s $OUTPUT/${NAME}.sam --outdir $SPLITSAM 
