#!/bin/bash
#PBS -M jrbnewman@ufl.edu
#PBS -m n
#PBS -w group_list=concannon
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/patcon/fnew/scripts/PBS_LOGS/sas
#PBS -l walltime=8:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=4gb
#PBS -t 2


### 54, no 6???

module load sas/9.3

#Set up variables

PROJ=/scratch/lfs/patcon/jnewman
SCRIPTS=$PROJ/scripts/sas

LOGS=$PROJ/sas_analysis/sas_logs
if [ ! -e $LOGS ]; then mkdir -p $LOGS; fi

SASDATA=$PROJ/sas_analysis/sas_data
if [ ! -e $SASDATA ]; then mkdir -p $SASDATA; fi

OUTDIR=/scratch/lfs/patcon/jnewman/eqtls/results
if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi

TMPDIR=/scratch/lfs/patcon/jnewman/sas_temp/temp_${PBS_ARRAYID}
if [ ! -e $TMPDIR ]; then mkdir -p $TMPDIR; fi

cd $SASDATA

sas -log $LOGS/eqtls_${PBS_ARRAYID}.log -work $TMPDIR -sysin $SCRIPTS/run_eqtl_anova2.sas -sysparm ${PBS_ARRAYID} -MEMSIZE 4g

rm $TMPDIR/*
