#!/bin/bash
#PBS -M jrbnewman@ufl.edu
#PBS -m n
#PBS -N hg19Aln
#PBS -w group_list=concannon
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/patcon/jnewman/scripts/PBS_LOGS/aln_splice
#PBS -l walltime=6:00:00
#PBS -l nodes=1:ppn=4
#PBS -l pmem=8gb
#PBS -t 4001-5024


###3348,3608,3516,3597,3979,3980,4813,4814,4815,4816,4872

##2000
##5024


module load bowtie/0.12.9
#module load last/247
module load python/2.7.3

## Store number of processors that will be used, i.e. the number of files we will split into to run LAST on
    NUMPROCS=4

## Set Directories
    PROJ=/scratch/lfs/patcon/jnewman

## We are aligning only the unique reads at this point 
    ORIG=/scratch/lfs/patcon/fnew/original_data/PC2009

## Get info from design file. Need a design file with unaligned reads from step 1 (aligning to junctions)
    DESIGN_FILE=/scratch/lfs/patcon/jnewman/new_design_file.csv
    DESIGN=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)
    IFS=',' read -ra ARRAY <<< "$DESIGN"

    FLOWCELL=${ARRAY[0]}
    LANE=${ARRAY[1]}
    REP=${ARRAY[2]}
    INDEX1=${ARRAY[3]}
    INDEX2=${ARRAY[4]}
    LIBRARY=${ARRAY[5]}

    NAME=${FLOWCELL}_${LANE}_1_${INDEX1}_${INDEX2}_${LIBRARY}
    READ1=$ORIG/${FLOWCELL}_${LANE}_1_${INDEX1}_${INDEX2}_${LIBRARY}.fastq
    READ2=$ORIG/${FLOWCELL}_${LANE}_2_${INDEX1}_${INDEX2}_${LIBRARY}.fastq

## Set Different References
    REF=/scratch/lfs/patcon/jnewman/references/splicing/hg19_splicing_catalogue_74bp_BT
    #LASTREF=/scratch/lfs/mcintyre/references/dmel_fb551/dmel-non-redundant-r5.51_fusions_LAST

## Create Necessary Folders
    OUTPUT=$PROJ/aln_splicing
    if [ ! -e $OUTPUT ] ; then mkdir -p $OUTPUT; fi

    # Create JOB LOG directory and start log
        LOGS=$OUTPUT/job_logs 
        ALN_ERROR_LOG=$LOGS/size_errors.txt
        if [ ! -d $LOGS ]; then mkdir -p $LOGS; fi

        MYLOG=$LOGS/${NAME}.log
        printf "`date` $NAME PBS_ARRAYID:$PBS_ARRAYID HOSTNAME:$HOSTNAME\n" > $MYLOG
    # Create ALN LOG directory
        ALNLOGS=$OUTPUT/aln_logs 
        if [ ! -d $ALNLOGS ]; then mkdir -p $ALNLOGS; fi

    # Create UNALN READ directory
        UNALNDIR=$OUTPUT/unaln_reads
        if [ ! -d $UNALNDIR ]; then mkdir -p $UNALNDIR; fi

# Select TMPDIR
    # Create a temporary folder to do everything in. If you comment this section
    # out, script will use node's local TMPDIR
    SIZE=`df /local/scratch/ | grep -v "Filesystem" | awk '{print $4}'`
    FLAG_SCRATCH=0
    #SIZE=1

    if [ $SIZE -lt 20000000 ]
    then 
        echo "TMPDIR full, moving to SCRATCH">>$MYLOG
        TMPDIR=/scratch/hpc/$USER/tmp/aln_splice_h19_$PBS_ARRAYID
        if [ ! -d $TMPDIR ]; then mkdir -p $TMPDIR; fi
        FLAG_SCRATCH=1
    fi
    printf "\----tmpdir: $TMPDIR \n"> $MYLOG


### FUNCTIONS FOR ALIGNMENT PIPELINE ###
# I have created a separate file that hold the alignment functions
source $PROJ/scripts/alignment_functions.sh

## Start Alignment Pipeline
    printf "<------------------- STARTING SE alignment process for $NAME [`date`] ------------------->\n" >> $MYLOG
    READS=$ORIG/${NAME}.fastq

    qual=`python /scratch/lfs/mcintyre/python.git/identify_quality.py -i $READS`
    if [ $qual == 'phred64' ]; 
    then 
        # set to old illumina quality scores phred64/solexa 1.3
        btqual='--phred64-quals'
        lastqual='3'
    else
        # change to sanger format which is what all new illumina data is
        btqual='--phred33-quals'
        lastqual='1'
    fi

    bowtie_se_all
    #last_se_uniq


## Combine all Sam files 
    echo "START Combine SAM files">>$MYLOG
    cat *.sam >$OUTPUT/${NAME}.sam 2>>$MYLOG
    echo "FINISH Combining SAM files [`date`]" >>$MYLOG

## Combine all Unaln FASTQ 
    echo "START Combine Unaln FQ">>$MYLOG
    cat *_unaln_bt.fq >$UNALNDIR/${NAME}_unaln.fq 2>>$MYLOG
    echo "FINISH Combining SAM files [`date`]" >>$MYLOG

## Remove TMPDIR if on SCRATCH
    DEL_TMP=1
    if [[ $FLAG_SCRATCH -eq 1 && $DEL_TMP -eq 1 ]]
    then
        cd ~
        rm -r $TMPDIR
    fi

echo "Script complete, [`date`]" >>$MYLOG
