#!/bin/bash
#PBS -M jrbnewman@ufl.edu
#PBS -m n
#PBS -N mm9_mpileup
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS-o /scratch/lfs/sugrue/scripts/PBS_logs
#PBS -l walltime=8:00:00
#PBS -l nodes=1:ppn=4
#PBS -l pmem=5gb
#PBS -t 1-64

#module load samtools/0.1.19 
module load samtools/1.1

#### mpileups

#### Set Directories
PROJ=/scratch/lfs/sugrue
INPUT=$PROJ/aln_splicing_distinct

#### I am using an SGE Array (pulls out each name from the file and calls it 'design')
DESIGN_FILE=$PROJ/design_files/sugrue_file_list.csv
DESIGN=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)

IFS=',' read -ra ARRAY <<< "$DESIGN"

     C=${ARRAY[0]}
     NUM=${ARRAY[1]}
     SAMP=${ARRAY[2]}
     LANE=${ARRAY[3]}
     READ=${ARRAY[4]}
     BIN=${ARRAY[5]}

     NAME=${C}-${NUM}_${SAMP}_${LANE}_${READ}_${BIN}


REF=/scratch/lfs/mcintyre/references/mm9/mm9_splicing_catalogue.fa
SAM=$INPUT/${FILE}.sam

#### create output directory
OUTPUT=$INPUT/splicing_mpileups
    if [ ! -e $OUTPUT ]; then mkdir -p $OUTPUT; fi
LOGS=$OUTPUT/logs
    if [ ! -e $LOGS ]; then mkdir $LOGS; fi
MYLOG=$LOGS/${FILE}_mpileup.log

#### Convert SAM to BAM
BAM=$INPUT/temp/${FILE}_aln
if [ ! -e $INPUT/temp ]; then mkdir $INPUT/temp; fi


echo `date`": Starting SAM to BAM conversion" > $MYLOG
samtools view  -u -t $REF.fai -o $BAM.bam $SAM 2>>$MYLOG
samtools sort -m 10000000000 $BAM.bam $BAM.sorted 2>>$MYLOG
samtools index $BAM.sorted.bam  >>$MYLOG
echo `date`": Finished SAM to BAM conversion" >> $MYLOG


#### Make mpileup
PILEUP=$OUTPUT/${FILE}_aln.mpileup

printf "`date` $FILE PBS_ID:$PBS_ARRAYID HOSTNAME:$HOSTNAME \n\n" >> $MYLOG

echo `date`": Generating pileup" >> $MYLOG

samtools mpileup -d 10000000000 -f $REF $BAM.sorted.bam  > $PILEUP 2>> $MYLOG

echo `date`": Finished" >> $MYLOG
