#!/bin/sh
#PBS -M jfear@ufl.edu
#PBS -m n
#PBS -r n
#PBS -q bio
#PBS -o /scratch/lfs/mcintyre/cegs_sem_sd_paper/scripts/PBS_LOGS/cegs_ag
#PBS -e /scratch/lfs/mcintyre/cegs_sem_sd_paper/scripts/PBS_LOGS/cegs_ag
#PBS -l walltime=11:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1gb

# Load required modules
module load python/2.7.6
module load sas/9.3

# Set up major variables
PROJ=/scratch/lfs/mcintyre/cegs_sem_sd_paper
PYSCRIPT=$PROJ/scripts/add_new_gene_to_network.py
ORIG=$PROJ/sas_data/cegsv_by_gene_sbs.sas7bdat

# Make a copy of the orignal data
cd $TMPDIR
cp $ORIG $TMPDIR/

# Iterate over Yps
WORK=$PROJ/cegs_adding_genes_yp2_no_tra_v2
PATHFILE=$PROJ/path_file/cegs_sex_determination_yp2_no_tra_v2.path

# Import gene name from the design fil
GENE=tra

# Build folder structure
echo "[`date`] Building Folder structure"
SASPROG=$WORK/sas_programs/$GENE
SASDAT=$WORK/sas_data 
GENLOG=$WORK/generation_logs        # Generation of SAS scripts
MODELLOG=$WORK/sem_logs/$GENE       # running SEMs
COMBLOG=$WORK/cat_logs              # Combining sas datasets together

for DIR in $SASPROG $SASDAT $MODELLOG $GENLOG $COMBLOG
do
    if [[ ! -e $DIR ]]; then mkdir -p $DIR; fi;
done

# Generate SAS models for GENE
echo "[`date`] Generating SEM models for $GENE"
python $PYSCRIPT -p $PATHFILE \
          -l $TMPDIR \
          -m $ORIG \
          -o $WORK/sas_programs/$GENE/$GENE.sas \
          -n $GENE \
          -g $GENE \
          --log $GENLOG/model_generation_${GENE}.log

# Run SAS Models
echo "[`date`] Running SEM models for $GENE"
for MODEL in $WORK/sas_programs/$GENE/$GENE*.sas
do
    NAME=`basename $MODEL .sas`
    sas -work $TMPDIR \
        -MEMSIZE 3g \
        -rsasuser \
        -nonews \
        -sysin $MODEL \
        -log $MODELLOG/${NAME}.log \
        -print /dev/null
done

echo "[`date`] Combining SEM models for $GENE"
sas -work $TMPDIR \
    -MEMSIZE 3g \
    -nonews \
    -rsasuser \
    -sysin $PROJ/sas_programs/combine_genome_wide_sem_models.sas \
    -log $COMBLOG/${GENE}.log \
    -print /dev/null \
    -sysparm "lib1=$TMPDIR,lib2=$WORK/sas_data,gene=$GENE"

# Delete current gene models to prepare for next iteration
rm gene_*.sas7bdat
echo "[`date`] Script complete"
