#!/bin/sh
#PBS -M jfear@ufl.edu
#PBS -m n
#PBS -r n
#PBS -q bio
#PBS -o /scratch/lfs/mcintyre/cegs_sem_sd_paper/scripts/PBS_LOGS/dspr_al
#PBS -e /scratch/lfs/mcintyre/cegs_sem_sd_paper/scripts/PBS_LOGS/dspr_al
#PBS -l walltime=11:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1gb

# Load required modules
module load python/2.7.6
module load sas/9.3

# Set up major variables
PROJ=/scratch/lfs/mcintyre/cegs_sem_sd_paper
PYSCRIPT=$PROJ/scripts/add_new_links_to_network.py
ORIG=$PROJ/sas_data/dsrp_sbs_gene_level_sym.sas7bdat

DESIGN_FILE=$PROJ/design_file/dspr_gene_list.csv

# Make a copy of the orignal data
cd $TMPDIR
cp $ORIG $TMPDIR/

# Iterate over Yps
WORK=$PROJ/dspr_adding_links_yp2_fullcov
PATHFILE=$PROJ/path_file/dspr_sex_determination_gene_yp2_fullcov.path

# Build folder structure
echo "[`date`] Building Folder structure"
SASPROG=$WORK/sas_programs
SASDAT=$WORK/sas_data
GENLOG=$WORK/generation_logs          # Generation of SAS scripts
MODELLOG=$WORK/sem_logs               # running SEMs
COMBLOG=$WORK/cat_logs                # Combining sas datasets together

for DIR in $SASPROG $SASDAT $MODELLOG $GENLOG $COMBLOG
do
    if [[ ! -e $DIR ]]; then mkdir -p $DIR; fi;
done

# Generate SAS models for each TARGET
echo "[`date`] Generating SEM models for Yp2 fullcov"
python $PYSCRIPT -p $PATHFILE \
          -l $TMPDIR \
          -m $ORIG \
          -o $WORK/sas_programs/yp2_fullcov.sas \
          --log $GENLOG/model_generation_yp2_fullcov.log

# Run SAS Models
echo "[`date`] Running SEM models for Yp2 fullcov"
for MODEL in $WORK/sas_programs/yp2_fullcov*.sas
do
    NAME=`basename $MODEL .sas`
    sas -work $TMPDIR \
        -MEMSIZE 3g \
        -nonews \
        -rsasuser \
        -sysin $MODEL \
        -log $MODELLOG/${NAME}.log \
        -print /dev/null
done

echo "[`date`] Combining SEM models for yp2_fullcov"
sas -work $TMPDIR \
    -MEMSIZE 3g \
    -nonews \
    -rsasuser \
    -sysin $PROJ/sas_programs/combine_genome_wide_sem_models.sas \
    -log $COMBLOG/yp2_fullcov.log \
    -print /dev/null \
    -sysparm "lib1=$TMPDIR,lib2=$WORK/sas_data,gene=None"

# Delete current gene models to prepare for next iteration
rm gene_*.sas7bdat
echo "[`date`] Script complete"
